name: generate_dpi

packages:
  - resources
  - apps

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  build_all:
    run: dart pub global run melos exec --depends-on="build_runner" "flutter packages pub run build_runner build"
    description: build_runner build all modules.

  build_resources:
    run: dart pub global run melos exec --fail-fast --scope="*resources*" --depends-on="build_runner" "flutter packages pub run build_runner build"
    description: build_runner build data module.

  force_build_all:
    run: dart pub global run melos exec --depends-on="build_runner" "flutter packages pub run build_runner build --delete-conflicting-outputs"
    description: build_runner build all modules.z

  l10n:
    run: dart pub global run melos exec --fail-fast --scope="*resources*" --flutter -- flutter pub run intl_utils:generate
    description: Generates l10n for all app packages.

  pub_upgrade:
    run: dart pub global run melos exec --fail-fast "flutter pub upgrade"
    description: Run pub upgrade on all module.

  lint:
    run: dart pub global run melos run analyze && dart pub global run melos run metrics
    description: Run metrics and analyze.